-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.artist
(
    id serial NOT NULL,
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    name_en character varying(100) COLLATE pg_catalog."default",
    category character varying(50) COLLATE pg_catalog."default",
    image_url character varying(500) COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT now(),
    CONSTRAINT artist_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.artist_poi
(
    artist_id integer NOT NULL,
    poi_id integer NOT NULL,
    relationship_type character varying(50) COLLATE pg_catalog."default" DEFAULT 'FILMING_AT'::character varying,
    CONSTRAINT artist_poi_pkey PRIMARY KEY (artist_id, poi_id)
);

CREATE TABLE IF NOT EXISTS public.course_template
(
    id serial NOT NULL,
    title character varying(200) COLLATE pg_catalog."default",
    title_en character varying(200) COLLATE pg_catalog."default",
    duration_days smallint,
    category character varying(30) COLLATE pg_catalog."default",
    transport character varying(20) COLLATE pg_catalog."default",
    estimated_cost integer,
    poi_ids integer[],
    route_geom geometry(LineString,4326),
    description text COLLATE pg_catalog."default",
    description_en text COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT now(),
    CONSTRAINT course_template_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.district_danger
(
    id serial NOT NULL,
    sido character varying(20) COLLATE pg_catalog."default" NOT NULL,
    sigungu character varying(30) COLLATE pg_catalog."default" NOT NULL,
    crash_count integer DEFAULT 0,
    death_count integer DEFAULT 0,
    severe_count integer DEFAULT 0,
    injury_count integer DEFAULT 0,
    raw_score numeric(10, 2),
    danger_score numeric(6, 4),
    geom geometry(Point,4326),
    data_year smallint,
    source character varying(50) COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT now(),
    CONSTRAINT district_danger_pkey PRIMARY KEY (id),
    CONSTRAINT district_danger_sido_sigungu_data_year_key UNIQUE (sido, sigungu, data_year)
);

CREATE TABLE IF NOT EXISTS public.poi
(
    id serial NOT NULL,
    name character varying(200) COLLATE pg_catalog."default" NOT NULL,
    name_en character varying(200) COLLATE pg_catalog."default",
    category character varying(30) COLLATE pg_catalog."default" NOT NULL,
    sub_category character varying(50) COLLATE pg_catalog."default",
    sido character varying(20) COLLATE pg_catalog."default",
    sigungu character varying(30) COLLATE pg_catalog."default",
    address character varying(300) COLLATE pg_catalog."default",
    geom geometry(Point,4326),
    description text COLLATE pg_catalog."default",
    description_en text COLLATE pg_catalog."default",
    source character varying(50) COLLATE pg_catalog."default",
    score numeric(3, 2),
    visit_count integer DEFAULT 0,
    image_url character varying(500) COLLATE pg_catalog."default",
    tags text[] COLLATE pg_catalog."default",
    phone character varying(30) COLLATE pg_catalog."default",
    url character varying(500) COLLATE pg_catalog."default",
    is_24h boolean DEFAULT false,
    raw_data jsonb,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    CONSTRAINT poi_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.trail
(
    id serial NOT NULL,
    name character varying(200) COLLATE pg_catalog."default",
    trail_type character varying(20) COLLATE pg_catalog."default",
    sido character varying(20) COLLATE pg_catalog."default",
    sigungu character varying(30) COLLATE pg_catalog."default",
    length_km numeric(8, 3),
    width_m numeric(6, 2),
    difficulty smallint,
    has_stamp boolean DEFAULT false,
    is_official boolean DEFAULT false,
    safety_index numeric(6, 4),
    road_type character varying(50) COLLATE pg_catalog."default",
    start_lat numeric(10, 7),
    start_lon numeric(10, 7),
    end_lat numeric(10, 7),
    end_lon numeric(10, 7),
    geom geometry(LineString,4326),
    source character varying(50) COLLATE pg_catalog."default",
    road_id character varying(200) COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT now(),
    CONSTRAINT trail_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.weather_daily
(
    id serial NOT NULL,
    stn_id character varying(10) COLLATE pg_catalog."default" NOT NULL,
    stn_name character varying(30) COLLATE pg_catalog."default",
    sido character varying(20) COLLATE pg_catalog."default",
    obs_date date NOT NULL,
    avg_temp numeric(5, 1),
    min_temp numeric(5, 1),
    max_temp numeric(5, 1),
    precipitation numeric(7, 1),
    avg_wind_spd numeric(5, 1),
    avg_humidity numeric(5, 1),
    sunshine_hr numeric(5, 1),
    geom geometry(Point,4326),
    created_at timestamp without time zone DEFAULT now(),
    CONSTRAINT weather_daily_pkey PRIMARY KEY (id),
    CONSTRAINT weather_daily_stn_id_obs_date_key UNIQUE (stn_id, obs_date)
);

ALTER TABLE IF EXISTS public.artist_poi
    ADD CONSTRAINT artist_poi_artist_id_fkey FOREIGN KEY (artist_id)
    REFERENCES public.artist (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.artist_poi
    ADD CONSTRAINT artist_poi_poi_id_fkey FOREIGN KEY (poi_id)
    REFERENCES public.poi (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;