-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.content
(
    content_id bigserial NOT NULL,
    content character varying(255) COLLATE pg_catalog."default",
    date character varying(255) COLLATE pg_catalog."default",
    del_dt timestamp(6) without time zone,
    del_yn character varying(255) COLLATE pg_catalog."default" NOT NULL DEFAULT 'N'::character varying,
    content_status character varying(255) COLLATE pg_catalog."default",
    content_type character varying(255) COLLATE pg_catalog."default",
    email character varying(255) COLLATE pg_catalog."default",
    emotion integer,
    frst_reg_ip character varying(255) COLLATE pg_catalog."default",
    last_updt_dt character varying(255) COLLATE pg_catalog."default",
    last_updt_ip character varying(255) COLLATE pg_catalog."default",
    reg_dt timestamp(6) without time zone,
    role_nm character varying(255) COLLATE pg_catalog."default",
    selected_times jsonb,
    title character varying(255) COLLATE pg_catalog."default",
    updt_dt timestamp(6) without time zone,
    user_id character varying(255) COLLATE pg_catalog."default",
    user_sqno bigint,
    daily_slots jsonb DEFAULT '{}'::jsonb,
    day_tag1 character varying(255) COLLATE pg_catalog."default",
    day_tag2 character varying(255) COLLATE pg_catalog."default",
    day_tag3 character varying(255) COLLATE pg_catalog."default",
    frst_dt timestamp(6) without time zone,
    frst_rgst_usps_sqno numeric(38, 0),
    last_updt_usps_sqno numeric(38, 0),
    role_cd character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT content_pkey PRIMARY KEY (content_id)
    );


CREATE TABLE IF NOT EXISTS public.goal_settings
(
    id bigserial NOT NULL,
    user_sqno bigint NOT NULL,
    user_id character varying(50) COLLATE pg_catalog."default",
    target_time timestamp without time zone NOT NULL,
    recorded_time timestamp without time zone,
    todays_message character varying(255) COLLATE pg_catalog."default",
    status character varying(20) COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT goal_settings_pkey PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS public.query_master
(
    sql_key character varying(100) COLLATE pg_catalog."default" NOT NULL,
    query_text text COLLATE pg_catalog."default" NOT NULL,
    return_type character varying(20) COLLATE pg_catalog."default",
    description text COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    required_params character varying(255) COLLATE pg_catalog."default",
    param_mapping jsonb,
    use_redis_yn character(1) COLLATE pg_catalog."default" DEFAULT 'N'::bpchar,
    redis_ttl_sec integer DEFAULT 3600,
    CONSTRAINT query_master_pkey PRIMARY KEY (sql_key)
    );

CREATE TABLE IF NOT EXISTS public.refresh_token
(
    user_sqno bigint NOT NULL,
    email character varying(255) COLLATE pg_catalog."default",
    expiration timestamp(6) without time zone,
    refresh_token character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT refresh_token_pkey PRIMARY KEY (user_sqno)
    );

CREATE TABLE IF NOT EXISTS public.ui_metadata
(
    ui_id bigserial NOT NULL,
    screen_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    component_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    label_text character varying(100) COLLATE pg_catalog."default" NOT NULL,
    component_type character varying(20) COLLATE pg_catalog."default" NOT NULL,
    sort_order integer NOT NULL,
    is_required boolean DEFAULT false,
    is_readonly boolean DEFAULT true,
    default_value text COLLATE pg_catalog."default",
    placeholder text COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    css_class character varying(100) COLLATE pg_catalog."default",
    inline_style text COLLATE pg_catalog."default",
    action_type character varying(50) COLLATE pg_catalog."default",
    action_url character varying(255) COLLATE pg_catalog."default",
    data_sql_key character varying(100) COLLATE pg_catalog."default",
    data_api_url character varying(255) COLLATE pg_catalog."default",
    data_params character varying(50) COLLATE pg_catalog."default",
    ref_data_id character varying(100) COLLATE pg_catalog."default",
    group_id character varying(50) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    group_direction character varying(10) COLLATE pg_catalog."default" DEFAULT 'COLUMN'::character varying,
    submit_group_id character varying(50) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    submit_group_order integer,
    submit_group_separator character varying(5) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    parent_group_id character varying(50) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    is_visible character varying(50) COLLATE pg_catalog."default" DEFAULT true,
    component_props jsonb DEFAULT '{}'::jsonb,
    allowed_roles character varying(255) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    label_text_overrides jsonb,
    css_class_overrides jsonb,
    CONSTRAINT ui_metadata_pkey PRIMARY KEY (ui_id),
    CONSTRAINT uq_screen_component UNIQUE (screen_id, component_id)
    );

COMMENT ON TABLE public.ui_metadata
    IS '화면 항목 구성을 위한 메타데이터 테이블';

COMMENT ON COLUMN public.ui_metadata.ui_id
    IS '화면 식별 코드';


COMMENT ON COLUMN public.ui_metadata.component_id
    IS 'DB에 저장될 필드명 (예: title)';

COMMENT ON COLUMN public.ui_metadata.label_text
    IS '사용자에게 보여줄 이름 (예: 제목)';

COMMENT ON COLUMN public.ui_metadata.component_type
    IS '입력 도구 종류 (TEXT, TEXTAREA, SELECT, DATE)';

COMMENT ON COLUMN public.ui_metadata.sort_order
    IS '화면 표시 순서';

COMMENT ON COLUMN public.ui_metadata.is_required
    IS '필수 입력 여부';

COMMENT ON COLUMN public.ui_metadata.is_readonly
    IS '입력 가능 여부(상세 화면은 Y, 작성화면은 N)';

COMMENT ON COLUMN public.ui_metadata.allowed_roles
    IS '접근 가능한 역할 목록 (예: "ROLE_USER,ROLE_ADMIN"). NULL이면 모두 허용';

COMMENT ON COLUMN public.ui_metadata.label_text_overrides
    IS '역할별 label_text 오버라이드 (예: {"ROLE_ADMIN":"관리자용","ROLE_USER":"사용자용"})';

COMMENT ON COLUMN public.ui_metadata.css_class_overrides
    IS '역할별 css_class 오버라이드 (예: {"ROLE_ADMIN":"btn-danger","ROLE_USER":"btn-primary"})';

CREATE TABLE IF NOT EXISTS public.ui_role_permissions
(
    id serial NOT NULL,
    ui_id integer NOT NULL,
    role_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ui_role_permissions_pkey PRIMARY KEY (id),
    CONSTRAINT uq_ui_metadata_role UNIQUE (ui_id, role_name)
    );

CREATE TABLE IF NOT EXISTS public.users
(
    user_sqno bigserial NOT NULL,
    created_at timestamp(6) without time zone,
    del_yn character varying(255) COLLATE pg_catalog."default",
    drug_using_type character varying(255) COLLATE pg_catalog."default",
    email character varying(255) COLLATE pg_catalog."default",
    hashed_password character varying(255) COLLATE pg_catalog."default",
    password character varying(255) COLLATE pg_catalog."default",
    phone character varying(255) COLLATE pg_catalog."default",
    role character varying(255) COLLATE pg_catalog."default",
    time_using_type character varying(255) COLLATE pg_catalog."default",
    social_type character varying(255) COLLATE pg_catalog."default",
    updated_at timestamp(6) without time zone,
    user_id character varying(50) COLLATE pg_catalog."default",
    verification_code character varying(255) COLLATE pg_catalog."default",
    verification_expired_at timestamp(6) without time zone,
    verify_yn character varying(255) COLLATE pg_catalog."default",
    withdraw_at timestamp(6) without time zone,
    detail_address character varying(255) COLLATE pg_catalog."default",
    road_address character varying(255) COLLATE pg_catalog."default",
    zip_code character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT users_pkey PRIMARY KEY (user_sqno)
    );


ALTER TABLE IF EXISTS public.ui_role_permissions
    ADD CONSTRAINT fk_ui_metadata FOREIGN KEY (ui_id)
    REFERENCES public.ui_metadata (ui_id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE CASCADE;

END;