-- Generated by Gemini at 2026-03-10
-- This script replaces all occurrences of 'DIARY' with 'CONTENT' and 'diary' with 'content'
-- in all text-based columns of the 'ui_metadata' table.

-- screen_id: character varying
UPDATE ui_metadata SET screen_id = replace(screen_id, 'DIARY', 'CONTENT') WHERE screen_id LIKE '%DIARY%';
UPDATE ui_metadata SET screen_id = replace(screen_id, 'diary', 'content') WHERE screen_id LIKE '%diary%';

-- component_id: character varying
UPDATE ui_metadata SET component_id = replace(component_id, 'DIARY', 'CONTENT') WHERE component_id LIKE '%DIARY%';
UPDATE ui_metadata SET component_id = replace(component_id, 'diary', 'content') WHERE component_id LIKE '%diary%';

-- label_text: character varying
UPDATE ui_metadata SET label_text = replace(label_text, 'DIARY', 'CONTENT') WHERE label_text LIKE '%DIARY%';
UPDATE ui_metadata SET label_text = replace(label_text, 'diary', 'content') WHERE label_text LIKE '%diary%';

-- component_type: character varying
UPDATE ui_metadata SET component_type = replace(component_type, 'DIARY', 'CONTENT') WHERE component_type LIKE '%DIARY%';
UPDATE ui_metadata SET component_type = replace(component_type, 'diary', 'content') WHERE component_type LIKE '%diary%';

-- default_value: text
UPDATE ui_metadata SET default_value = replace(default_value, 'DIARY', 'CONTENT') WHERE default_value LIKE '%DIARY%';
UPDATE ui_metadata SET default_value = replace(default_value, 'diary', 'content') WHERE default_value LIKE '%diary%';

-- placeholder: text
UPDATE ui_metadata SET placeholder = replace(placeholder, 'DIARY', 'CONTENT') WHERE placeholder LIKE '%DIARY%';
UPDATE ui_metadata SET placeholder = replace(placeholder, 'diary', 'content') WHERE placeholder LIKE '%diary%';

-- css_class: character varying
UPDATE ui_metadata SET css_class = replace(css_class, 'DIARY', 'CONTENT') WHERE css_class LIKE '%DIARY%';
UPDATE ui_metadata SET css_class = replace(css_class, 'diary', 'content') WHERE css_class LIKE '%diary%';

-- inline_style: text
UPDATE ui_metadata SET inline_style = replace(inline_style, 'DIARY', 'CONTENT') WHERE inline_style LIKE '%DIARY%';
UPDATE ui_metadata SET inline_style = replace(inline_style, 'diary', 'content') WHERE inline_style LIKE '%diary%';

-- action_type: character varying
UPDATE ui_metadata SET action_type = replace(action_type, 'DIARY', 'CONTENT') WHERE action_type LIKE '%DIARY%';
UPDATE ui_metadata SET action_type = replace(action_type, 'diary', 'content') WHERE action_type LIKE '%diary%';

-- action_url: character varying
UPDATE ui_metadata SET action_url = replace(action_url, 'DIARY', 'CONTENT') WHERE action_url LIKE '%DIARY%';
UPDATE ui_metadata SET action_url = replace(action_url, 'diary', 'content') WHERE action_url LIKE '%diary%';

-- data_sql_key: character varying
UPDATE ui_metadata SET data_sql_key = replace(data_sql_key, 'DIARY', 'CONTENT') WHERE data_sql_key LIKE '%DIARY%';
UPDATE ui_metadata SET data_sql_key = replace(data_sql_key, 'diary', 'content') WHERE data_sql_key LIKE '%diary%';

-- data_api_url: character varying
UPDATE ui_metadata SET data_api_url = replace(data_api_url, 'DIARY', 'CONTENT') WHERE data_api_url LIKE '%DIARY%';
UPDATE ui_metadata SET data_api_url = replace(data_api_url, 'diary', 'content') WHERE data_api_url LIKE '%diary%';

-- data_params: character varying
UPDATE ui_metadata SET data_params = replace(data_params, 'DIARY', 'CONTENT') WHERE data_params LIKE '%DIARY%';
UPDATE ui_metadata SET data_params = replace(data_params, 'diary', 'content') WHERE data_params LIKE '%diary%';

-- ref_data_id: character varying
UPDATE ui_metadata SET ref_data_id = replace(ref_data_id, 'DIARY', 'CONTENT') WHERE ref_data_id LIKE '%DIARY%';
UPDATE ui_metadata SET ref_data_id = replace(ref_data_id, 'diary', 'content') WHERE ref_data_id LIKE '%diary%';

-- group_id: character varying
UPDATE ui_metadata SET group_id = replace(group_id, 'DIARY', 'CONTENT') WHERE group_id LIKE '%DIARY%';
UPDATE ui_metadata SET group_id = replace(group_id, 'diary', 'content') WHERE group_id LIKE '%diary%';

-- group_direction: character varying
UPDATE ui_metadata SET group_direction = replace(group_direction, 'DIARY', 'CONTENT') WHERE group_direction LIKE '%DIARY%';
UPDATE ui_metadata SET group_direction = replace(group_direction, 'diary', 'content') WHERE group_direction LIKE '%diary%';

-- submit_group_id: character varying
UPDATE ui_metadata SET submit_group_id = replace(submit_group_id, 'DIARY', 'CONTENT') WHERE submit_group_id LIKE '%DIARY%';
UPDATE ui_metadata SET submit_group_id = replace(submit_group_id, 'diary', 'content') WHERE submit_group_id LIKE '%diary%';

-- submit_group_separator: character varying
UPDATE ui_metadata SET submit_group_separator = replace(submit_group_separator, 'DIARY', 'CONTENT') WHERE submit_group_separator LIKE '%DIARY%';
UPDATE ui_metadata SET submit_group_separator = replace(submit_group_separator, 'diary', 'content') WHERE submit_group_separator LIKE '%diary%';

-- parent_group_id: character varying
UPDATE ui_metadata SET parent_group_id = replace(parent_group_id, 'DIARY', 'CONTENT') WHERE parent_group_id LIKE '%DIARY%';
UPDATE ui_metadata SET parent_group_id = replace(parent_group_id, 'diary', 'content') WHERE parent_group_id LIKE '%diary%';

-- is_visible: character varying
UPDATE ui_metadata SET is_visible = replace(is_visible, 'DIARY', 'CONTENT') WHERE is_visible LIKE '%DIARY%';
UPDATE ui_metadata SET is_visible = replace(is_visible, 'diary', 'content') WHERE is_visible LIKE '%diary%';

-- allowed_roles: character varying
UPDATE ui_metadata SET allowed_roles = replace(allowed_roles, 'DIARY', 'CONTENT') WHERE allowed_roles LIKE '%DIARY%';
UPDATE ui_metadata SET allowed_roles = replace(allowed_roles, 'diary', 'content') WHERE allowed_roles LIKE '%diary%';

-- component_props: jsonb
UPDATE ui_metadata SET component_props = replace(component_props::text, 'DIARY', 'CONTENT')::jsonb WHERE component_props::text LIKE '%DIARY%';
UPDATE ui_metadata SET component_props = replace(component_props::text, 'diary', 'content')::jsonb WHERE component_props::text LIKE '%diary%';

-- label_text_overrides: jsonb
UPDATE ui_metadata SET label_text_overrides = replace(label_text_overrides::text, 'DIARY', 'CONTENT')::jsonb WHERE label_text_overrides::text LIKE '%DIARY%';
UPDATE ui_metadata SET label_text_overrides = replace(label_text_overrides::text, 'diary', 'content')::jsonb WHERE label_text_overrides::text LIKE '%diary%';

-- css_class_overrides: jsonb
UPDATE ui_metadata SET css_class_overrides = replace(css_class_overrides::text, 'DIARY', 'CONTENT')::jsonb WHERE css_class_overrides::text LIKE '%DIARY%';
UPDATE ui_metadata SET css_class_overrides = replace(css_class_overrides::text, 'diary', 'content')::jsonb WHERE css_class_overrides::text LIKE '%diary%';

