inference_address=http://0.0.0.0:8085
management_address=http://0.0.0.0:8086
metrics_address=http://0.0.0.0:7070
model_store=/home/model-store
load_models=all
number_of_gpu=1
default_workers_per_model=1
job_queue_size=100
batch_size=4
max_batch_delay=100
