export const SCREEN_MAP: Record<string, string> = {
    "/": "MAIN_PAGE",
    "/MAIN_PAGE": "MAIN_PAGE",
    "/LOGIN_PAGE": "LOGIN_PAGE",
    "/SET_TIME_PAGE": "SET_TIME_PAGE" ,
    "/TUTORIAL_PAGE" : "TUTORIAL_PAGE",
    "/CONTENT_LIST": "CONTENT_LIST",
    "/CONTENT_WRITE": "CONTENT_WRITE",
    "/CONTENT_DETAIL" : "CONTENT_DETAIL",
    "/CONTENT_MODIFY" : "CONTENT_MODIFY",
    // "/MY_PAGE": "MY_PAGE",
    // "/DASHBOARD_PAGE": "DASHBOARD_PAGE",
    "/AI_ENGLISH_CHAT_PAGE": "AI_ENGLISH_CHAT_PAGE",
    "/AI_JAPANESE_CHAT_PAGE": "AI_JAPANESE_CHAT_PAGE",
    "/AI_KOREAN_CHAT_PAGE": "AI_KOREAN_CHAT_PAGE",
    "/MEMBERSHIP_SHOP_PAGE": "MEMBERSHIP_SHOP_PAGE",
    "/GOOGLE_CALLBACK": "GOOGLE_CALLBACK",
};

export const DEFAULT_SCREEN_ID = "MAIN_PAGE";